# Generated by Django 2.1.4 on 2019-09-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('binNum', models.IntegerField()),
                ('wrongCount', models.IntegerField()),
                ('nextReviewAt', models.DateTimeField()),
            ],
        ),
    ]
